server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1058050958802-cus5mo8f79r3mpve2vg1ebedgvmcq9op.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

    datasource:
      url: jdbc:mysql://mysql:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456


  mvc:
    locale: vi_VN

  messages:
    basename: messages
    encoding: UTF-8

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "H35ZLxHVhpqJ/HzHxIGyHCOkBYbmL/9e3xPZ7Yn5CzQepN4cIqJwEcS9orBFk38Q"
