package com.example.YummyDaily.exception;

import lombok.*;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;

@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
@AllArgsConstructor
@Getter
public enum ErrorCode {
    SUCCESS(1000, "Thành công", HttpStatus.OK), // Added for successful operations
    USER_EXISTED(1002, "Người dùng đã tồn tại", HttpStatus.BAD_REQUEST),
    USER_NOT_EXISTED(1005, "Người dùng không tồn tại", HttpStatus.NOT_FOUND),
    USERNAME_INVALID(1003, "Tên đăng nhập phải có ít nhất 5 ký tự", HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID(1004, "Mật khẩu phải có ít nhất 5 ký tự", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(1007, "Email không hợp lệ", HttpStatus.BAD_REQUEST),
    EMAIL_EXISTED(1008, "Email đã được sử dụng", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1006, "Người dùng chưa xác thực", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1009, "Người dùng không có quyền truy cập", HttpStatus.FORBIDDEN),
    INVALID_ROLE(1010, "Vai trò không hợp lệ", HttpStatus.BAD_REQUEST),
    ACCOUNT_LOCKED(1011, "Tài khoản đã bị khóa", HttpStatus.FORBIDDEN),
    INVALID_PASSWORD(1012, "Mật khẩu không đúng", HttpStatus.UNAUTHORIZED),
    INVALID_LOGIN(1012, "Tên tài khoản hoặc mật khẩu không đúng", HttpStatus.UNAUTHORIZED),
    AVATAR_URL_INVALID(1014, "Ảnh đại diện phải là URL hợp lệ", HttpStatus.BAD_REQUEST),
    OPERATION_FAILED(1015, "Thao tác không thành công", HttpStatus.INTERNAL_SERVER_ERROR),
    RESOURCE_NOT_FOUND(1016, "Không tìm thấy tài nguyên", HttpStatus.NOT_FOUND),
    SERVER_ERROR(5000, "Lỗi hệ thống", HttpStatus.INTERNAL_SERVER_ERROR),
    UNCATEGORIZED_EXCEPTION(9999, "Lỗi không xác định", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_NOT_FOUND(404, "Người dùng không tồn tại.", HttpStatus.NOT_FOUND),
    USERNAME_ALREADY_EXISTS(400, "Tên người dùng đã tồn tại. Vui lòng chọn tên khác.", HttpStatus.BAD_REQUEST),
    INVALID_KEY(1001, "Invalid message key", HttpStatus.BAD_REQUEST),
    PASSWORD_TOO_SHORT(1013, "Mật khẩu phải có ít nhất 8 ký tự", HttpStatus.BAD_REQUEST),
    EMAIL_FORMAT_INVALID(1017, "Định dạng email không hợp lệ", HttpStatus.BAD_REQUEST),
    FULLNAME_INVALID(1018, "Tên đầy đủ chỉ được chứa các ký tự chữ cái và khoảng trắng", HttpStatus.BAD_REQUEST),
    ROLE_INVALID(1019, "Vai trò không hợp lệ (chỉ có thể là 'admin' hoặc 'user')", HttpStatus.BAD_REQUEST),
    USERNAME_FORMAT_INVALID(1021, "Tên người dùng chỉ có thể chứa chữ cái, số và dấu gạch dưới", HttpStatus.BAD_REQUEST),
    INVALID_TOKEN(1022, "Token không hợp lệ hoặc đã hết hạn", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(1023, "Không có quyền truy cập vào tài nguyên này", HttpStatus.FORBIDDEN),
    CATEGORY_EXISTED(1024, "Danh mục đã tồn tại", HttpStatus.CONFLICT),
    CATEGORY_NOT_EXISTED(1025, "Danh mục không tồn tại", HttpStatus.NOT_FOUND),
    INGREDIENT_NOT_EXISTED(1026, "Nguyên liệu không tồn tại", HttpStatus.NOT_FOUND),
    INGREDIENT_EXISTED(1027, "Nguyên liệu đã tồn tại", HttpStatus.CONFLICT),
    RECIPE_NOT_EXISTED(1028, "Công thức không tồn tại", HttpStatus.NOT_FOUND),
    RECIPE_EXISTED(1029, "Công thức đã tồn tại", HttpStatus.CONFLICT),
    INGREDIENT_NAME_REQUIRED(1031, "Tên nguyên liệu không được để trống", HttpStatus.BAD_REQUEST),
    INGREDIENT_NAME_INVALID(1032, "Tên nguyên liệu phải từ 2 đến 50 ký tự", HttpStatus.BAD_REQUEST),
    INGREDIENT_UNIT_REQUIRED(1033, "Đơn vị nguyên liệu không được để trống", HttpStatus.BAD_REQUEST),
    INGREDIENT_UNIT_INVALID(1034, "Đơn vị nguyên liệu phải từ 1 đến 20 ký tự", HttpStatus.BAD_REQUEST),
    INGREDIENT_IMAGE_REQUIRED(1035, "URL hình ảnh nguyên liệu không được để trống", HttpStatus.BAD_REQUEST),
    INGREDIENT_IMAGE_INVALID(1036, "URL hình ảnh nguyên liệu không hợp lệ", HttpStatus.BAD_REQUEST),
    CATEGORY_NAME_REQUIRED(1040, "Tên danh mục không được để trống", HttpStatus.BAD_REQUEST),
    CATEGORY_NAME_INVALID(1041, "Tên danh mục phải từ 2 đến 50 ký tự", HttpStatus.BAD_REQUEST),
    CATEGORY_IMAGE_REQUIRED(1042, "URL hình ảnh danh mục không được để trống", HttpStatus.BAD_REQUEST),
    CATEGORY_IMAGE_INVALID(1043, "URL hình ảnh danh mục không hợp lệ", HttpStatus.BAD_REQUEST),
    RECIPE_NAME_REQUIRED(1050, "Tên công thức không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_NAME_INVALID(1051, "Tên công thức phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    RECIPE_DESCRIPTION_REQUIRED(1052, "Mô tả công thức không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_DESCRIPTION_INVALID(1053, "Mô tả công thức phải từ 10 đến 500 ký tự", HttpStatus.BAD_REQUEST),
    RECIPE_IMAGE_REQUIRED(1054, "URL hình ảnh công thức không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_IMAGE_INVALID(1055, "URL hình ảnh công thức không hợp lệ", HttpStatus.BAD_REQUEST),
    RECIPE_COOKING_TIME_INVALID(1056, "Thời gian nấu phải lớn hơn 0 phút", HttpStatus.BAD_REQUEST),
    RECIPE_DIFFICULTY_REQUIRED(1057, "Cấp độ khó không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_VIEW_INVALID(1058, "Số lượt xem không hợp lệ", HttpStatus.BAD_REQUEST),
    RECIPE_USER_ID_REQUIRED(1059, "ID người dùng không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_CATEGORY_ID_REQUIRED(1060, "ID danh mục không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_NUMBER_PEOPLE_INVALID(1061, "Số người ăn phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    RECIPE_GENERATED_DATE_INVALID(1062, "Ngày tạo công thức không hợp lệ", HttpStatus.BAD_REQUEST),
    RECIPE_STATE_REQUIRED(1063, "Trạng thái công thức không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_VIDEO_REQUIRED(1064, "URL video giới thiệu không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_VIDEO_INVALID(1065, "URL video giới thiệu không hợp lệ", HttpStatus.BAD_REQUEST),
    RECIPE_FAVORITE_REQUIRED(1066, "Trạng thái yêu thích không được để trống", HttpStatus.BAD_REQUEST),
    RECIPE_ID_REQUIRED(1070, "ID công thức không được để trống", HttpStatus.BAD_REQUEST),
    STEP_NUMBER_REQUIRED(1071, "Số bước nấu không được để trống", HttpStatus.BAD_REQUEST),
    STEP_NUMBER_INVALID(1072, "Số bước nấu phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    STEP_DESCRIPTION_REQUIRED(1073, "Mô tả bước nấu không được để trống", HttpStatus.BAD_REQUEST),
    STEP_IMAGE_REQUIRED(1074, "Hình ảnh bước nấu không được để trống", HttpStatus.BAD_REQUEST),
    STEP_IMAGE_INVALID(1075, "Hình ảnh bước nấu phải là URL hợp lệ", HttpStatus.BAD_REQUEST),
    STEP_NOT_FOUND(1076, "Bước nấu ăn không tồn tại", HttpStatus.NOT_FOUND),
    RATING_SCORE_INVALID(1080, "Điểm đánh giá phải từ 1 đến 5", HttpStatus.BAD_REQUEST),
    RATING_IMAGE_INVALID(1081, "URL hình ảnh đánh giá không hợp lệ", HttpStatus.BAD_REQUEST),
    RATING_DESCRIPTION_REQUIRED(1082, "Mô tả đánh giá không được để trống", HttpStatus.BAD_REQUEST),
    RATING_DESCRIPTION_INVALID(1083, "Mô tả đánh giá phải từ 10 đến 500 ký tự", HttpStatus.BAD_REQUEST),
    PERMISSION_DENIED(1081, "Bạn không có quyền thực hiện thao tác này", HttpStatus.FORBIDDEN),
    INVALID_STATE(1082, "Trạng thái không hợp lệ", HttpStatus.BAD_REQUEST),
    USER_FAVORITE_EXISTED(1090, "Công thức đã có trong danh sách yêu thích", HttpStatus.CONFLICT),
    USER_FAVORITE_NOT_FOUND(1091, "Yêu thích không tồn tại", HttpStatus.NOT_FOUND),
    USER_FAVORITE_CREATE_FAILED(1092, "Không thể thêm vào danh sách yêu thích", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_FAVORITE_UPDATE_FAILED(1093, "Cập nhật yêu thích thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_FAVORITE_DELETE_FAILED(1094, "Xóa yêu thích thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_FAVORITE_INVALID_REQUEST(1095, "Yêu cầu không hợp lệ cho danh sách yêu thích", HttpStatus.BAD_REQUEST),
    NOTIFICATION_RECIPIENT_REQUIRED(1100, "Người nhận thông báo không được để trống", HttpStatus.BAD_REQUEST),
    NOTIFICATION_ROLE_REQUIRED(1101, "Vai trò của người nhận không được để trống", HttpStatus.BAD_REQUEST),
    NOTIFICATION_TITLE_REQUIRED(1102, "Tiêu đề thông báo không được để trống", HttpStatus.BAD_REQUEST),
    NOTIFICATION_MESSAGE_REQUIRED(1103, "Nội dung thông báo không được để trống", HttpStatus.BAD_REQUEST),
    NOTIFICATION_TYPE_REQUIRED(1104, "Loại thông báo không được để trống", HttpStatus.BAD_REQUEST),
    NOTIFICATION_CREATION_FAILED(1105, "Không thể tạo thông báo", HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_NOT_FOUND(1106, "Không tìm thấy thông báo", HttpStatus.NOT_FOUND),
    NOTIFICATION_SAVE_FAILED(1107, "Lưu thông báo thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    COOKINGSTEP_REQUIRED(1108, "Các bước nấu ăn không được để trống", HttpStatus.BAD_REQUEST),
    RATING_NOT_FOUND(1009, "Đánh giá không tồn tại", HttpStatus.NOT_FOUND);

    int code;
    String message;
    HttpStatus statuscode;
}